### PR TITLE
[MRG] Fix#421 pass stopThr to the sinkhorn function in empirical_sinkhorn_divergence

### PR DESCRIPTION
**Pull request by tlacombe**
## Types of changes

Variable default values. 

## Motivation and context / Related issue

Fix small typo in the code, where the parameter `stopThr` in `empirical_sinkhorn_divergence` was useless because subcalls used `stopThr=1e-9` instead of `stopThr=stopThr`. 

Same for a similar instance occuring in `sinkhorn_epsilon_scaling`. 

Documented in Issue #421 .

## PR checklist

- [x] I have read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x] The documentation is up-to-date with the changes I made (check build artifacts).
- [x] All tests passed, and additional code has been **covered with new tests**.
- [x] I have added the PR and Issue fix to the [**RELEASES.md**](RELEASES.md) file.

### CODE REVIEW

**Comment by tlacombe** [comment]
It seems the doc build fails because of an issue with `plot_gromov_barycenter.py`.

```
Unexpected failing examples:
/home/circleci/project/examples/gromov/plot_gromov_barycenter.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/circleci/project/examples/gromov/plot_gromov_barycenter.py", line 113, in <module>
    xs = np.array([np.array(xs[0]), np.array(xs[1]),
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```

 Did I do something wrong? I don't understand what I've done that could affect this example.

**Comment by rflamary** [comment]
I just launched the run for doc build in CI l'et us see what is happening. This is weird indeed.

**Comment by rflamary** [comment]
ok this is a new bug that appeared recently I will look into it.

Thanks for the PR it looks perfect I will mere it as soon as I handled this weird new bug.

**Comment by rflamary** [comment]
Thanks very much for the two PR @tlacombe it is appreciated

**Pull request merged**
