### PR TITLE
[FIX] numerical errors in ot.gmm

### PR DESCRIPTION
**Pull request by samuelbx**
## Motivation and context / Related issue
This PR fixes numerical instability issues in `ot.gmm` in the `gaussian_pdf`and `gmm_ot_apply_map` methods, arising when handling high-dimensional Gaussians (see #689).

### Key changes
- [x] added `slogdet` (computing the log determinant of a matrix) to the backend
- [x] added a `ot.gmm.gaussian_logpdf` function to compute log density using `slogdet`
- [x] replaced fractions of densities in `gmm_ot_apply_map` by exp of difference of log densities

## How has this been tested (if it applies)
- [x] existing GMM examples produce identical results
- [x] linux-minimal-deps tests OK

## PR checklist

- [x] I have read the [**CONTRIBUTING**](https://pythonot.github.io/contributing.html) document.
- [x] The documentation is up-to-date with the changes I made (check build artifacts).
- [x] All tests passed, and additional code has been **covered with new tests**.
- [x] I have added the PR and Issue fix to the [**RELEASES.md**](RELEASES.md) file.

### CODE REVIEW

**Comment by eloitanguy** [comment]
hi, thanks for the contribution! This is will be a great first PR :)
The build and tests seem to fail due to #688 , i'm looking into it.
In the meantime, here's a few things you can look at:
- In my opinion, we should keep the Cholesky backend function.
- It seems that you could vectorise the `for` loops at [line 328](https://github.com/PythonOT/POT/pull/690/files#diff-f007d235a8968b995c6374ba9b8cea9c2ca691b01d45806b023e0bdfb3ab277cR328) and [line 361](https://github.com/PythonOT/POT/pull/690/files#diff-f007d235a8968b995c6374ba9b8cea9c2ca691b01d45806b023e0bdfb3ab277cR361)
- please remove [line 313](https://github.com/PythonOT/POT/pull/690/files#diff-f007d235a8968b995c6374ba9b8cea9c2ca691b01d45806b023e0bdfb3ab277cR313), I should have done so myself earlier

Once the `cvxpy` issue is resolved, I'll have a closer look (especially at tests) with a code review :D

**Comment by samuelbx** [comment]
@eloitanguy thanks for your feedback! I've just done the vectorization part as you suggested. regarding cholesky backend: I initially added it for a task that didn't require it in the end and just forgot to remove it, which I've done in a later commit

**Comment by eloitanguy** [comment]
Hi, excellent work again! The code looks good and the documentation examples worked perfectly, nothing to add there.

We need to test your function `slogdet` in `test_backend`, you can take inspiration from [L390](https://github.com/PythonOT/POT/blob/master/test/test_backend.py#L390) and [L314](https://github.com/PythonOT/POT/blob/master/test/test_backend.py#L134) which tests `det` (you have two outputs so you may need to stack them into an array or have two entries for the two coordinates). Feel free to ask for help, testing can be tricky!

Please add your contribution (PR + Issue resolved in the `RELEASES.md` file, and add yourself to `CONTRIBUTORS.md` :)

**Comment by rflamary** [comment]
Welcome to POT contributors @samuelbx

**Pull request merged**
